stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - deploy-ltwa
  environment:
    name: production
  only:
    - main
  script:
    - set-env DB_NAME=$DB_NAME DB_PASSWORD=$DB_PASSWORD DB_USER=$DB_USER DB_HOST=$DB_HOST DB_PORT=$DB_PORT JWT_SETTINGS_ISSUER=$JWT_SETTINGS_ISSUER JWT_SETTINGS_AUDIENCE=$JWT_SETTINGS_AUDIENCE JWT_SETTINGS_KEY=$JWT_SETTINGS_KEY
    - git-push main
  
  #  - printenv > .env
  #  - scp .env dokku@localhost:$CI_PROJECT_NAME-$CI_PROJECT_ID/.env
  #  - git push dokku@localhost:$CI_PROJECT_NAME-$CI_PROJECT_ID HEAD:refs/heads/main
  #  - git-push main
  #- git push --force dokku@localhost:$CI_PROJECT_NAME-$CI_PROJECT_ID HEAD:refs/heads/main

variables:
  GIT_CLEAN_FLAGS: none